
-- ---------------------------------------------------------
-- 1. SEQUENCES
-- ---------------------------------------------------------
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE APPLICANT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE OFFICER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE POLICE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE APPLICATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE LICENSE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PERMIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE VIOLATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PAYMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE NOTIF_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TEST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SCHEDULE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE RESULT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MED_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DOC_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE AUDIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ---------------------------------------------------------
-- 2. TABLES
-- ---------------------------------------------------------
CREATE TABLE DLMS_USER (
    USER_ID NUMBER(19) PRIMARY KEY,
    CNIC VARCHAR2(15) NOT NULL UNIQUE,
    FULL_NAME_EN VARCHAR2(255) NOT NULL,
    FULL_NAME_UR VARCHAR2(255),
    FATHER_NAME VARCHAR2(255),
    DOB DATE,
    GENDER VARCHAR2(10),
    BLOOD_GROUP VARCHAR2(5),
    MOBILE_NUMBER VARCHAR2(15),
    EMAIL VARCHAR2(255) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(50) NOT NULL,
    ACCOUNT_STATUS VARCHAR2(20),
    DISTRICT VARCHAR2(100)
);

CREATE TABLE APPLICANT (
    APPLICANT_ID NUMBER(19) PRIMARY KEY,
    USER_ID NUMBER(19) NOT NULL UNIQUE,
    PREF_LANGUAGE VARCHAR2(10),
    REG_DATE DATE,
    CONSTRAINT FK_APPLICANT_USER FOREIGN KEY (USER_ID) REFERENCES DLMS_USER(USER_ID)
);

CREATE TABLE LICENSING_OFFICER (
    OFFICER_ID NUMBER(19) PRIMARY KEY,
    USER_ID NUMBER(19) NOT NULL UNIQUE,
    DEPARTMENT VARCHAR2(255),
    CONSTRAINT FK_LIC_OFFICER_USER FOREIGN KEY (USER_ID) REFERENCES DLMS_USER(USER_ID)
);

CREATE TABLE TESTING_OFFICER (
    OFFICER_ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER(19) NOT NULL UNIQUE,
    ASSIGNED_CENTER VARCHAR2(255),
    CONSTRAINT FK_TEST_OFFICER_USER FOREIGN KEY (USER_ID) REFERENCES DLMS_USER(USER_ID)
);

CREATE TABLE TRAFFIC_POLICE_OFFICER (
    POLICE_OFFICER_ID NUMBER(19) PRIMARY KEY,
    USER_ID NUMBER(19) UNIQUE,
    BADGE_NUMBER VARCHAR2(100),
    STATION_NAME VARCHAR2(255),
    RANK VARCHAR2(100),
    CONSTRAINT FK_POLICE_USER FOREIGN KEY (USER_ID) REFERENCES DLMS_USER(USER_ID)
);

CREATE TABLE APPLICATION (
    APPLICATION_ID NUMBER(19) PRIMARY KEY,
    APPLICANT_ID NUMBER(19) NOT NULL,
    LICENSE_CATEGORY VARCHAR2(10),
    APPLICATION_TYPE VARCHAR2(30),
    APPLICATION_STATUS VARCHAR2(50),
    SUBMISSION_DATE DATE,
    LAST_UPDATED_DATE TIMESTAMP,
    REJECTION_REASON VARCHAR2(500),
    CURRENT_STAGE VARCHAR2(50),
    OFFICER_ID NUMBER(19),
    THEORY_ATTEMPTS NUMBER(10) DEFAULT 0,
    CONSTRAINT FK_APP_APPLICANT FOREIGN KEY (APPLICANT_ID) REFERENCES APPLICANT(APPLICANT_ID),
    CONSTRAINT FK_APP_OFFICER FOREIGN KEY (OFFICER_ID) REFERENCES LICENSING_OFFICER(OFFICER_ID)
);

CREATE TABLE APPLICATION_DOCUMENT (
    DOCUMENT_ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    APPLICATION_ID NUMBER(19) NOT NULL,
    DOCUMENT_TYPE VARCHAR2(50) NOT NULL,
    FILE_PATH VARCHAR2(500) NOT NULL,
    FILE_SIZE NUMBER(19),
    VERIFICATION_STATUS VARCHAR2(50),
    UPLOAD_DATE TIMESTAMP,
    REJECTION_REASON VARCHAR2(500),
    CONSTRAINT FK_DOC_APP FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATION(APPLICATION_ID)
);

CREATE TABLE MEDICAL_CERTIFICATE (
    CERTIFICATE_ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    APPLICATION_ID NUMBER(19) NOT NULL,
    TEST_OFFICER_ID NUMBER(19),
    STATUS VARCHAR2(50),
    APPROVAL_DATE TIMESTAMP,
    REJECTION_REASON VARCHAR2(500),
    FILE_PATH VARCHAR2(500) NOT NULL,
    CONSTRAINT FK_MED_APP FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATION(APPLICATION_ID),
    CONSTRAINT FK_MED_OFFICER FOREIGN KEY (TEST_OFFICER_ID) REFERENCES TESTING_OFFICER(OFFICER_ID)
);

CREATE TABLE LEARNER_PERMIT (
    PERMIT_ID NUMBER(19) PRIMARY KEY,
    LEARNER_PERMIT_NO VARCHAR2(50) UNIQUE,
    APPLICATION_ID NUMBER(19) NOT NULL UNIQUE,
    ISSUE_DATE DATE,
    EXPIRY_DATE DATE,
    STATUS VARCHAR2(20),
    CONSTRAINT FK_PERMIT_APP FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATION(APPLICATION_ID)
);

CREATE TABLE DRIVING_LICENSE (
    LICENSE_ID NUMBER(19) PRIMARY KEY,
    LICENSE_NUMBER VARCHAR2(50) UNIQUE,
    APPLICATION_ID NUMBER(19) NOT NULL UNIQUE,
    APPLICANT_ID NUMBER(19) NOT NULL,
    CATEGORY VARCHAR2(20),
    OFFICER_ID NUMBER(19),
    ISSUE_DATE DATE,
    EXPIRY_DATE DATE,
    STATUS VARCHAR2(20),
    QR_CODE_DATA VARCHAR2(500),
    TOTAL_PENALTY_POINTS NUMBER(10) DEFAULT 0,
    SUSPENSION_END_DATE DATE,
    CONSTRAINT FK_LIC_APP FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATION(APPLICATION_ID),
    CONSTRAINT FK_LIC_APPLICANT FOREIGN KEY (APPLICANT_ID) REFERENCES APPLICANT(APPLICANT_ID),
    CONSTRAINT FK_LIC_OFFICER FOREIGN KEY (OFFICER_ID) REFERENCES LICENSING_OFFICER(OFFICER_ID)
);

CREATE TABLE QUESTION (
    ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TEXT VARCHAR2(1000),
    OPTION_A VARCHAR2(255),
    OPTION_B VARCHAR2(255),
    OPTION_C VARCHAR2(255),
    OPTION_D VARCHAR2(255),
    CORRECT_OPTION VARCHAR2(10)
);

CREATE TABLE THEORY_TEST_ATTEMPT (
    ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    APPLICATION_ID NUMBER(19),
    ATTEMPT_NUMBER NUMBER(10),
    SCORE NUMBER(10),
    PASSED NUMBER(1), -- Boolean 0 or 1
    ATTEMPT_DATE TIMESTAMP,
    CONSTRAINT FK_THEORY_APP FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATION(APPLICATION_ID)
);

CREATE TABLE THEORY_TEST_DETAIL (
    ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ATTEMPT_ID NUMBER(19),
    QUESTION_ID NUMBER(19),
    SELECTED_OPTION VARCHAR2(10),
    IS_CORRECT NUMBER(1), -- Boolean 0 or 1
    CONSTRAINT FK_DETAIL_ATTEMPT FOREIGN KEY (ATTEMPT_ID) REFERENCES THEORY_TEST_ATTEMPT(ID),
    CONSTRAINT FK_DETAIL_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID)
);

CREATE TABLE DRIVING_TEST_SCHEDULE (
    ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    APPLICATION_ID NUMBER(19) UNIQUE,
    EXAMINER_OFFICER_ID NUMBER(19),
    SCHEDULED_DATE DATE,
    TEST_CENTER VARCHAR2(255),
    STATUS VARCHAR2(50),
    CONSTRAINT FK_PRACTICAL_APP FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATION(APPLICATION_ID),
    CONSTRAINT FK_PRACTICAL_EXAMINER FOREIGN KEY (EXAMINER_OFFICER_ID) REFERENCES TESTING_OFFICER(OFFICER_ID)
);

CREATE TABLE PRACTICAL_TEST_RESULT (
    ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    APPLICATION_ID NUMBER(19) UNIQUE,
    PARKING_SCORE NUMBER(10),
    LANE_SCORE NUMBER(10),
    SIGN_SCORE NUMBER(10),
    TOTAL_SCORE NUMBER(10),
    STATUS VARCHAR2(50),
    EVALUATION_DATE TIMESTAMP,
    CONSTRAINT FK_RESULT_APP FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATION(APPLICATION_ID)
);

CREATE TABLE TRAFFIC_VIOLATION (
    VIOLATION_ID NUMBER(19) PRIMARY KEY,
    LICENSE_ID NUMBER(19) NOT NULL,
    POLICE_OFFICER_ID NUMBER(19),
    CHALLAN_NO VARCHAR2(255) UNIQUE,
    VIOLATION_TYPE VARCHAR2(255),
    FINE_AMOUNT NUMBER(10,2),
    PENALTY_POINTS NUMBER(10),
    VIOLATION_DATE DATE,
    VIOLATION_LOCATION VARCHAR2(255),
    VEHICLE_REG_NO VARCHAR2(255),
    CHALLAN_STATUS VARCHAR2(20),
    CONSTRAINT FK_VIOLATION_LICENSE FOREIGN KEY (LICENSE_ID) REFERENCES DRIVING_LICENSE(LICENSE_ID),
    CONSTRAINT FK_VIOLATION_POLICE FOREIGN KEY (POLICE_OFFICER_ID) REFERENCES TRAFFIC_POLICE_OFFICER(POLICE_OFFICER_ID)
);

CREATE TABLE PAYMENT (
    PAYMENT_ID NUMBER(19) PRIMARY KEY,
    USER_ID NUMBER(19) NOT NULL,
    APPLICATION_ID NUMBER(19) NOT NULL,
    AMOUNT NUMBER(19,4) NOT NULL,
    PAYMENT_METHOD VARCHAR2(100),
    PAYMENT_STATUS VARCHAR2(50),
    PAYMENT_TYPE VARCHAR2(50),
    TRANSACTION_ID VARCHAR2(255),
    PAYMENT_DATE TIMESTAMP,
    CHALLAN_NO VARCHAR2(255) UNIQUE,
    REVIEWED_BY_OFFICER_ID NUMBER(19),
    REMARKS VARCHAR2(1000),
    CONSTRAINT FK_PAYMENT_USER FOREIGN KEY (USER_ID) REFERENCES DLMS_USER(USER_ID),
    CONSTRAINT FK_PAYMENT_APP FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATION(APPLICATION_ID)
);

CREATE TABLE PAYMENT_AUDIT_LOG (
    AUDIT_ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PAYMENT_ID NUMBER(19) NOT NULL,
    ACTION_TAKEN VARCHAR2(255) NOT NULL,
    REMARKS VARCHAR2(1000),
    OFFICER_ID NUMBER(19) NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL,
    CONSTRAINT FK_AUDIT_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID)
);

CREATE TABLE NOTIFICATION (
    NOTIFICATION_ID NUMBER(19) PRIMARY KEY,
    USER_ID NUMBER(19) NOT NULL,
    TYPE VARCHAR2(30),
    SUBJECT VARCHAR2(255),
    MESSAGE_BODY VARCHAR2(1000),
    SENT_AT TIMESTAMP,
    IS_READ NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_NOTIF_USER FOREIGN KEY (USER_ID) REFERENCES DLMS_USER(USER_ID)
);

-- =======================================================================
-- 3. INDEXES
-- =======================================================================

-- 1. User & Applicant Searches (Speeds up the "Verify License" tab)
CREATE INDEX IDX_USER_EMAIL      ON DLMS_USER(EMAIL);
CREATE INDEX IDX_USER_CNIC       ON DLMS_USER(CNIC);

-- 2. Application Tracking (Speeds up Applicant Dashboard loading)
CREATE INDEX IDX_APP_STATUS      ON APPLICATION(APPLICATION_STATUS);
CREATE INDEX IDX_APP_STAGE       ON APPLICATION(CURRENT_STAGE);
CREATE INDEX IDX_APP_APPLICANT   ON APPLICATION(APPLICANT_ID);

-- 3. License & Enforcement (Speeds up Police Challan generation)
CREATE INDEX IDX_LICENSE_STATUS  ON DRIVING_LICENSE(STATUS);
CREATE INDEX IDX_LICENSE_NUM     ON DRIVING_LICENSE(LICENSE_NUMBER);
CREATE INDEX IDX_VIO_LICENSE     ON TRAFFIC_VIOLATION(LICENSE_ID);
CREATE INDEX IDX_VIO_CHALLAN     ON TRAFFIC_VIOLATION(CHALLAN_NO);

-- 4. Testing & Medical
CREATE INDEX IDX_TEST_APP        ON DRIVING_TEST_SCHEDULE(APPLICATION_ID);
CREATE INDEX IDX_MED_APP         ON MEDICAL_CERTIFICATE(APPLICATION_ID);

-- ---------------------------------------------------------
-- 4. VIEWS
-- ---------------------------------------------------------

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW V_GLOBAL_OFFICER_AUDIT ("OFFICER_ID", "MODULE", "ACTION_TYPE", "DESCRIPTION", "ACTION_DATE") AS 
SELECT 
    officer_id,
    'FINANCE' AS module,
    action_taken AS action_type,
    'Processed Payment ID: ' || payment_id || ' | Remarks: ' || remarks AS description,
    timestamp AS action_date
FROM PAYMENT_AUDIT_LOG
WHERE officer_id IS NOT NULL

UNION ALL

-- 2. Medical Officer Actions
SELECT 
    test_officer_id AS officer_id,
    'MEDICAL' AS module,
    'CERT_' || status AS action_type,
    'Reviewed Medical Cert ID: ' || certificate_id || ' | Status set to: ' || status AS description,
    approval_date AS action_date
FROM MEDICAL_CERTIFICATE
WHERE test_officer_id IS NOT NULL AND approval_date IS NOT NULL

UNION ALL

-- 3. Testing Examiner Actions (Practical Tests)
SELECT 
    examiner_officer_id AS officer_id,
    'TESTING' AS module,
    'TEST_' || status AS action_type,
    'Evaluated Practical Test for App ID: ' || application_id || ' | Result: ' || status AS description,
    scheduled_date AS action_date
FROM DRIVING_TEST_SCHEDULE
WHERE examiner_officer_id IS NOT NULL AND status IN ('COMPLETED', 'PASSED', 'FAILED')

UNION ALL

-- 4. Traffic Police Actions (Enforcement)
SELECT 
    police_officer_id AS officer_id,
    'ENFORCEMENT' AS module,
    'CHALLAN_ISSUED' AS action_type,
    'Issued Challan: ' || challan_no || ' for ' || REPLACE(violation_type, '_', ' ') || ' (Fine: PKR ' || fine_amount || ')' AS description,
    violation_date AS action_date
FROM TRAFFIC_VIOLATION
WHERE police_officer_id IS NOT NULL;


CREATE OR REPLACE FORCE NONEDITIONABLE VIEW VW_APPLICANT_DASHBOARD ("CNIC", "FULL_NAME_EN", "DISTRICT", "APPLICATION_ID", "LICENSE_CATEGORY", "APPLICATION_TYPE", "APPLICATION_STATUS", "CURRENT_STAGE", "LEARNER_PERMIT_NO", "LEARNER_EXPIRY", "LICENSE_NUMBER", "LICENSE_STATUS") AS 
SELECT 
    u.cnic,
    u.full_name_en,
    u.district,
    app.application_id,
    app.license_category,
    app.application_type,
    app.application_status,
    app.current_stage,
    lp.learner_permit_no,
    lp.expiry_date AS learner_expiry,
    dl.license_number,
    dl.status AS license_status
FROM APPLICANT a
JOIN DLMS_USER u ON a.user_id = u.user_id
JOIN APPLICATION app ON a.applicant_id = app.applicant_id
LEFT JOIN LEARNER_PERMIT lp ON app.application_id = lp.application_id
LEFT JOIN DRIVING_LICENSE dl ON app.application_id = dl.application_id;


CREATE OR REPLACE FORCE NONEDITIONABLE VIEW VW_CENTER_PERFORMANCE ("TEST_CENTER", "TOTAL_TESTS_CONDUCTED", "TOTAL_PASSED", "TOTAL_FAILED", "PASS_RATE_PERCENTAGE") AS 
SELECT 
    s.test_center,
    COUNT(r.id) AS total_tests_conducted,
    SUM(CASE WHEN r.status = 'PASSED' THEN 1 ELSE 0 END) AS total_passed,
    SUM(CASE WHEN r.status = 'FAILED' THEN 1 ELSE 0 END) AS total_failed,
    ROUND((SUM(CASE WHEN r.status = 'PASSED' THEN 1 ELSE 0 END) / NULLIF(COUNT(r.id), 0)) * 100, 2) AS pass_rate_percentage
FROM driving_test_schedule s
JOIN practical_test_result r ON s.application_id = r.application_id
GROUP BY s.test_center;


CREATE OR REPLACE FORCE NONEDITIONABLE VIEW VW_FINANCIAL_RECONCILIATION ("PAYMENT_ID", "CHALLAN_NO", "PAYMENT_TYPE", "AMOUNT", "PAYMENT_STATUS", "PAYMENT_DATE", "PAYMENT_METHOD", "TRANSACTION_ID", "PAYER_CNIC", "APPLICATION_ID", "LICENSE_CATEGORY", "APPLICATION_TYPE") AS 
SELECT 
    p.payment_id,
    p.challan_no,
    p.payment_type,
    p.amount,
    p.payment_status,
    p.payment_date,
    p.payment_method,
    p.transaction_id,
    u.cnic AS payer_cnic,
    app.application_id,
    app.license_category,
    app.application_type
FROM PAYMENT p
JOIN APPLICATION app ON p.application_id = app.application_id
JOIN DLMS_USER u ON p.user_id = u.user_id;


CREATE OR REPLACE FORCE NONEDITIONABLE VIEW VW_HIGH_RISK_DRIVERS ("LICENSE_NUMBER", "FULL_NAME_EN", "CNIC", "MOBILE_NUMBER", "TOTAL_PENALTY_POINTS", "LICENSE_STATUS", "SUSPENSION_END_DATE") AS 
SELECT 
    dl.license_number,
    u.full_name_en,
    u.cnic,
    u.mobile_number,
    dl.total_penalty_points,
    dl.status AS license_status,
    dl.suspension_end_date
FROM DRIVING_LICENSE dl
JOIN APPLICANT a ON dl.applicant_id = a.applicant_id
JOIN DLMS_USER u ON a.user_id = u.user_id
WHERE dl.total_penalty_points >= 20;

-- ---------------------------------------------------------
-- 5. PROCEDURES
-- ---------------------------------------------------------

create or replace NONEDITIONABLE PROCEDURE SP_AUTO_UNBLOCK_LICENSE (p_license_id IN NUMBER) AS
BEGIN
    UPDATE DRIVING_LICENSE
    SET status = 'ACTIVE', total_penalty_points = 0, suspension_end_date = NULL
    WHERE license_id = p_license_id 
      AND status = 'SUSPENDED' 
      AND suspension_end_date < SYSDATE;
    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_CREATE_LEARNER_PERMIT (
    p_applicant_user_email IN VARCHAR2,
    p_category             IN VARCHAR2,
    p_application_id       OUT NUMBER
) AS
    v_applicant_id NUMBER;
    v_user_id      NUMBER;
    v_challan_no   VARCHAR2(50);
BEGIN
    SELECT a.applicant_id, a.user_id INTO v_applicant_id, v_user_id
    FROM APPLICANT a JOIN DLMS_USER u ON a.user_id = u.user_id WHERE u.email = p_applicant_user_email;

    SELECT APPLICATION_SEQ.NEXTVAL INTO p_application_id FROM DUAL;

    INSERT INTO APPLICATION (application_id, applicant_id, license_category, application_type, application_status, submission_date, current_stage) 
    VALUES (p_application_id, v_applicant_id, p_category, 'NEW', 'PENDING', SYSDATE, 'LEARNER_PAYMENT_PENDING');

    v_challan_no := 'CHL-' || TO_CHAR(SYSDATE, 'YYYY') || '-APP-' || p_application_id;

    INSERT INTO PAYMENT (payment_id, application_id, user_id, challan_no, amount, payment_type, payment_status) 
    VALUES (PAYMENT_SEQ.NEXTVAL, p_application_id, v_user_id, v_challan_no, 300.0, 'LEARNER_FEE', 'PENDING_CHALLAN');
    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_CREATE_STAFF (
    p_full_name  IN VARCHAR2,
    p_cnic       IN VARCHAR2,
    p_email      IN VARCHAR2,
    p_password   IN VARCHAR2,
    p_role       IN VARCHAR2,
    p_department IN VARCHAR2 DEFAULT NULL,
    p_center     IN VARCHAR2 DEFAULT NULL,
    p_badge      IN VARCHAR2 DEFAULT NULL,
    p_rank       IN VARCHAR2 DEFAULT NULL,
    p_station    IN VARCHAR2 DEFAULT NULL
) AS
    v_user_id NUMBER;
BEGIN
    SELECT USER_SEQ.NEXTVAL INTO v_user_id FROM DUAL;

    INSERT INTO DLMS_USER (user_id, cnic, full_name_en, email, password_hash, role, account_status) 
    VALUES (v_user_id, p_cnic, p_full_name, p_email, p_password, p_role, 'ACTIVE');

    IF p_role = 'LICENSING_OFFICER' THEN
        INSERT INTO LICENSING_OFFICER (officer_id, user_id, department) VALUES (OFFICER_SEQ.NEXTVAL, v_user_id, NVL(p_department, 'General'));
    ELSIF p_role = 'TESTING_OFFICER' THEN
        -- Using identity column for Testing Officer based on previous setup
        INSERT INTO TESTING_OFFICER (user_id, assigned_center) VALUES (v_user_id, NVL(p_center, 'Main Center'));
    ELSIF p_role = 'TRAFFIC_POLICE' THEN
        INSERT INTO TRAFFIC_POLICE_OFFICER (police_officer_id, user_id, badge_number, rank, station_name) VALUES (POLICE_SEQ.NEXTVAL, v_user_id, p_badge, p_rank, p_station);
    END IF;
    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_EVALUATE_PRACTICAL_TEST (
    p_application_id IN NUMBER,
    p_officer_id     IN NUMBER,
    p_parking_score  IN NUMBER,
    p_lane_score     IN NUMBER,
    p_sign_score     IN NUMBER,
    p_total_score    IN NUMBER
) AS
    v_status       VARCHAR2(20);
    v_user_id      NUMBER;
    v_challan_no   VARCHAR2(50);
BEGIN
    IF p_total_score >= 70 THEN v_status := 'PASSED'; ELSE v_status := 'FAILED'; END IF;

    UPDATE DRIVING_TEST_SCHEDULE 
    SET status = 'COMPLETED', examiner_officer_id = p_officer_id 
    WHERE application_id = p_application_id;

    -- Intentionally omitting ID here to prevent ORA-32795
    INSERT INTO PRACTICAL_TEST_RESULT (
        application_id, parking_score, lane_score, sign_score, total_score, status, evaluation_date
    ) VALUES (
        p_application_id, p_parking_score, p_lane_score, p_sign_score, p_total_score, v_status, SYSDATE
    );

    IF v_status = 'PASSED' THEN
        UPDATE APPLICATION SET current_stage = 'LICENSE_PAYMENT_PENDING' WHERE application_id = p_application_id;

        SELECT a.user_id INTO v_user_id FROM APPLICATION app JOIN APPLICANT a ON app.applicant_id = a.applicant_id WHERE app.application_id = p_application_id;

        v_challan_no := 'CHL-' || TO_CHAR(SYSDATE, 'YYYY') || '-LIC-' || p_application_id;

        INSERT INTO PAYMENT (payment_id, application_id, user_id, challan_no, amount, payment_type, payment_status)
        VALUES (PAYMENT_SEQ.NEXTVAL, p_application_id, v_user_id, v_challan_no, 2500.0, 'LICENSE_FEE', 'PENDING_CHALLAN');
    ELSE
        UPDATE APPLICATION SET current_stage = 'PRACTICAL_PENDING' WHERE application_id = p_application_id;
    END IF;

    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_ISSUE_LICENSE (
    p_app_id     IN NUMBER,
    p_officer_id IN NUMBER
) AS
    v_license_count NUMBER;
    v_applicant_id  NUMBER;
    v_category      VARCHAR2(20);
    v_license_no    VARCHAR2(50);
    v_qr_data       VARCHAR2(50);
BEGIN
    SELECT COUNT(*) INTO v_license_count FROM DRIVING_LICENSE WHERE application_id = p_app_id;
    IF v_license_count = 0 THEN
        SELECT applicant_id, license_category INTO v_applicant_id, v_category FROM APPLICATION WHERE application_id = p_app_id;

        v_license_no := 'PB-' || TO_CHAR(SYSDATE, 'YYYY') || '-' || p_app_id;
        v_qr_data := 'DLMS-' || DBMS_RANDOM.STRING('U', 8);

        INSERT INTO DRIVING_LICENSE (license_id, license_number, application_id, applicant_id, category, officer_id, status, issue_date, expiry_date, qr_code_data, total_penalty_points) 
        VALUES (LICENSE_SEQ.NEXTVAL, v_license_no, p_app_id, v_applicant_id, v_category, p_officer_id, 'ACTIVE', SYSDATE, ADD_MONTHS(SYSDATE, 60), v_qr_data, 0);

        UPDATE APPLICATION SET current_stage = 'COMPLETED' WHERE application_id = p_app_id;
    END IF;
    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_MARK_ALL_NOTIF_READ (p_user_id IN NUMBER) AS
BEGIN
    UPDATE NOTIFICATION SET is_read = 1 WHERE user_id = p_user_id AND is_read = 0;
    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_MARK_NOTIF_READ (p_notif_id IN NUMBER) AS
BEGIN
    UPDATE NOTIFICATION SET is_read = 1 WHERE notification_id = p_notif_id;
    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_PROCESS_PAYMENT_DECISION (
    p_payment_id   IN NUMBER,
    p_officer_id   IN NUMBER,
    p_action       IN VARCHAR2, 
    p_remarks      IN VARCHAR2
) AS
BEGIN
    UPDATE PAYMENT 
    SET payment_status = p_action, 
        reviewed_by_officer_id = p_officer_id, 
        remarks = p_remarks
    WHERE payment_id = p_payment_id;

    INSERT INTO PAYMENT_AUDIT_LOG (
        audit_id, payment_id, officer_id, action_taken, remarks, timestamp
    ) VALUES (
        AUDIT_SEQ.NEXTVAL, p_payment_id, p_officer_id, p_action, p_remarks, SYSDATE
    );
    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_RECORD_VIOLATION (
    p_license_id      IN NUMBER,
    p_officer_id      IN NUMBER,
    p_challan_no      IN VARCHAR2,
    p_vehicle_reg     IN VARCHAR2,
    p_violation_type  IN VARCHAR2,
    p_fine_amount     IN NUMBER,
    p_penalty_points  IN NUMBER,
    p_location        IN VARCHAR2
) AS
    v_current_points NUMBER;
BEGIN
    INSERT INTO TRAFFIC_VIOLATION (violation_id, license_id, police_officer_id, challan_no, vehicle_reg_no, violation_type, fine_amount, penalty_points, violation_location, violation_date, challan_status) 
    VALUES (VIOLATION_SEQ.NEXTVAL, p_license_id, p_officer_id, p_challan_no, p_vehicle_reg, p_violation_type, p_fine_amount, p_penalty_points, p_location, SYSDATE, 'PENDING');

    UPDATE DRIVING_LICENSE SET total_penalty_points = NVL(total_penalty_points, 0) + p_penalty_points
    WHERE license_id = p_license_id RETURNING total_penalty_points INTO v_current_points;

    IF v_current_points >= 30 THEN
        UPDATE DRIVING_LICENSE SET status = 'SUSPENDED', suspension_end_date = ADD_MONTHS(SYSDATE, 3) WHERE license_id = p_license_id;
    END IF;
    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_REGISTER_USER (
    p_cnic          IN VARCHAR2,
    p_full_name     IN VARCHAR2,
    p_email         IN VARCHAR2,
    p_password_hash IN VARCHAR2,
    p_mobile        IN VARCHAR2,
    p_district      IN VARCHAR2,
    p_gender        IN VARCHAR2,
    p_blood_group   IN VARCHAR2,
    p_user_id       OUT NUMBER
) AS
BEGIN
    SELECT USER_SEQ.NEXTVAL INTO p_user_id FROM DUAL;

    INSERT INTO DLMS_USER (user_id, cnic, full_name_en, email, password_hash, mobile_number, district, gender, blood_group, role, account_status) 
    VALUES (p_user_id, p_cnic, p_full_name, p_email, p_password_hash, p_mobile, p_district, p_gender, p_blood_group, 'APPLICANT', 'ACTIVE');

    INSERT INTO APPLICANT (applicant_id, user_id, pref_language, reg_date) 
    VALUES (APPLICANT_SEQ.NEXTVAL, p_user_id, 'EN', SYSDATE);

    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_REVIEW_MEDICAL_CERT (
    p_cert_id    IN NUMBER,
    p_officer_id IN NUMBER,
    p_status     IN VARCHAR2,
    p_comments   IN VARCHAR2
) AS
    v_app_id  NUMBER;
    v_user_id NUMBER;
    v_type    VARCHAR2(20);
BEGIN
    UPDATE MEDICAL_CERTIFICATE 
    SET status = p_status, 
        rejection_reason = p_comments, 
        approval_date = SYSDATE, 
        test_officer_id = p_officer_id
    WHERE certificate_id = p_cert_id 
    RETURNING application_id INTO v_app_id;

    SELECT a.user_id 
    INTO v_user_id 
    FROM APPLICATION app 
    JOIN APPLICANT a ON app.applicant_id = a.applicant_id 
    WHERE app.application_id = v_app_id;

    IF p_status = 'APPROVED' THEN
        UPDATE APPLICATION 
        SET current_stage = 'THEORY_PENDING' 
        WHERE application_id = v_app_id;
        v_type := 'SUCCESS';
    ELSE
        v_type := 'WARNING';
    END IF;

    -- NOTIFICATION_ID is NOT identity, so sequence is correct
    INSERT INTO NOTIFICATION (
        notification_id, user_id, type, subject, message_body, sent_at, is_read
    ) 
    VALUES (
        NOTIF_SEQ.NEXTVAL, v_user_id, v_type, 'Medical ' || p_status, p_comments, SYSDATE, 0
    );

    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_SAVE_MEDICAL_CERT (
    p_app_id    IN NUMBER,
    p_file_path IN VARCHAR2
) AS
BEGIN
    -- FIXED: Removed certificate_id, it is GENERATED ALWAYS AS IDENTITY
    INSERT INTO MEDICAL_CERTIFICATE (
        application_id, file_path, status
    ) VALUES (
        p_app_id, p_file_path, 'UNDER_REVIEW'
    );
    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_SAVE_NADRA_DOCUMENT (
    p_app_id    IN NUMBER,
    p_doc_type  IN VARCHAR2,
    p_file_path IN VARCHAR2,
    p_file_size IN NUMBER
) AS
    v_cnic_count  NUMBER;
    v_photo_count NUMBER;
BEGIN
    -- FIXED: Removed document_id, Oracle auto-generates it
    INSERT INTO APPLICATION_DOCUMENT (
        application_id, document_type, file_path, file_size, verification_status, upload_date
    ) VALUES (
        p_app_id, p_doc_type, p_file_path, p_file_size, 'VERIFIED', SYSDATE
    );

    -- Check if BOTH CNIC and PHOTO are verified to advance the stage
    SELECT COUNT(*) INTO v_cnic_count 
    FROM APPLICATION_DOCUMENT 
    WHERE application_id = p_app_id 
      AND document_type = 'CNIC_COPY' 
      AND verification_status = 'VERIFIED';

    SELECT COUNT(*) INTO v_photo_count 
    FROM APPLICATION_DOCUMENT 
    WHERE application_id = p_app_id 
      AND document_type = 'PHOTO' 
      AND verification_status = 'VERIFIED';

    IF v_cnic_count > 0 AND v_photo_count > 0 THEN
        UPDATE APPLICATION 
        SET current_stage = 'MEDICAL_PENDING' 
        WHERE application_id = p_app_id;
    END IF;

    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_SCHEDULE_TEST (
    p_application_id IN NUMBER,
    p_test_center    IN VARCHAR2,
    p_test_date      IN DATE
) AS
    v_daily_count NUMBER;
BEGIN
    -- Allow today or future dates. Reject only past dates.
    IF TRUNC(p_test_date) < TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20002, 'Test date cannot be in the past.');
    END IF;

    -- Check Capacity (30 limit)
    SELECT COUNT(*) INTO v_daily_count 
    FROM DRIVING_TEST_SCHEDULE
    WHERE TRUNC(scheduled_date) = TRUNC(p_test_date) 
    AND test_center = p_test_center
    AND status = 'SCHEDULED';

    IF v_daily_count >= 30 THEN 
        RAISE_APPLICATION_ERROR(-20001, 'Center is fully booked for this date.'); 
    END IF;

    -- Insert new schedule (NO ID COLUMN included)
    INSERT INTO DRIVING_TEST_SCHEDULE (application_id, test_center, scheduled_date, status) 
    VALUES (p_application_id, p_test_center, TRUNC(p_test_date), 'SCHEDULED');

    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_TOGGLE_STAFF_SUSPEND (p_user_id IN NUMBER) AS
    v_status VARCHAR2(20);
BEGIN
    SELECT account_status INTO v_status FROM DLMS_USER WHERE user_id = p_user_id;
    IF v_status = 'SUSPENDED' THEN
        UPDATE DLMS_USER SET account_status = 'ACTIVE' WHERE user_id = p_user_id;
    ELSE
        UPDATE DLMS_USER SET account_status = 'SUSPENDED' WHERE user_id = p_user_id;
    END IF;
    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_UPDATE_PAYMENT_SUBMIT (
    p_app_id         IN NUMBER,
    p_transaction_id IN VARCHAR2,
    p_payment_method IN VARCHAR2
) AS
    v_payment_type VARCHAR2(50);
BEGIN
    -- Update the latest pending payment for this application
    UPDATE PAYMENT 
    SET transaction_id = p_transaction_id, payment_method = p_payment_method, 
        payment_date = SYSDATE, payment_status = 'VERIFICATION_PENDING', remarks = NULL
    WHERE application_id = p_app_id AND payment_status = 'PENDING_CHALLAN'
    RETURNING payment_type INTO v_payment_type;

    -- Move Application Stage forward
    IF v_payment_type = 'LICENSE_FEE' THEN
        UPDATE APPLICATION SET current_stage = 'FINAL_PAYMENT_VERIFICATION' WHERE application_id = p_app_id;
    ELSE
        UPDATE APPLICATION SET current_stage = 'PAYMENT_VERIFICATION' WHERE application_id = p_app_id;
    END IF;

    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_UPDATE_STAFF (
    p_user_id       IN NUMBER,
    p_full_name     IN VARCHAR2,
    p_email         IN VARCHAR2,
    p_role          IN VARCHAR2,
    p_password_hash IN VARCHAR2
) AS
    v_email_count NUMBER;
BEGIN
    -- Check if email is taken by someone else
    SELECT COUNT(*) INTO v_email_count FROM DLMS_USER 
    WHERE email = p_email AND user_id != p_user_id;

    IF v_email_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Email is already taken by another user.');
    END IF;

    -- Update basic details
    UPDATE DLMS_USER 
    SET full_name_en = p_full_name, email = p_email, role = p_role 
    WHERE user_id = p_user_id;

    -- Update password only if provided
    IF p_password_hash IS NOT NULL THEN
        UPDATE DLMS_USER SET password_hash = p_password_hash WHERE user_id = p_user_id;
    END IF;

    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_WORKFLOW_REJECT_PAYMENT (
    p_app_id     IN NUMBER,
    p_officer_id IN NUMBER,
    p_reason     IN VARCHAR2
) AS
    v_payment_id   NUMBER;
    v_payment_type VARCHAR2(50);
    v_user_id      NUMBER;
    v_new_id       NUMBER; -- Variable to hold the ID
BEGIN
    -- 1. Find the latest payment
    SELECT payment_id, payment_type INTO v_payment_id, v_payment_type
    FROM PAYMENT WHERE application_id = p_app_id ORDER BY payment_id DESC FETCH FIRST 1 ROWS ONLY;

    -- 2. Update Payment
    UPDATE PAYMENT 
    SET payment_status = 'REJECTED', reviewed_by_officer_id = p_officer_id, remarks = p_reason
    WHERE payment_id = v_payment_id;

    -- 3. Audit Log
    INSERT INTO PAYMENT_AUDIT_LOG (payment_id, officer_id, action_taken, remarks, timestamp)
    VALUES (v_payment_id, p_officer_id, 'REJECTED', p_reason, SYSDATE);

    -- 4. Find User ID
    SELECT a.user_id INTO v_user_id FROM APPLICATION app 
    JOIN APPLICANT a ON app.applicant_id = a.applicant_id WHERE app.application_id = p_app_id;

    -- 5. Update Application Stage
    UPDATE APPLICATION 
    SET current_stage = DECODE(v_payment_type, 'LICENSE_FEE', 'LICENSE_FEE_PENDING', 'LEARNER_FEE_PENDING'), 
        application_status = 'REJECTED', rejection_reason = p_reason
    WHERE application_id = p_app_id;

    -- 6. CRITICAL FIX: Get ID from sequence first, then insert
    SELECT NOTIF_SEQ.NEXTVAL INTO v_new_id FROM DUAL;

    INSERT INTO NOTIFICATION (notification_id, user_id, type, subject, message_body, sent_at, is_read) 
    VALUES (v_new_id, v_user_id, 'PAYMENT_REJECTED', 'Payment Rejected', 'Your payment receipt was rejected. Reason: ' || p_reason, SYSDATE, 0);

    COMMIT;
END;
/

create or replace NONEDITIONABLE PROCEDURE SP_WORKFLOW_VERIFY_PAYMENT (
    p_app_id     IN NUMBER,
    p_officer_id IN NUMBER
) AS
    v_payment_id      NUMBER;
    v_payment_type    VARCHAR2(50);
    v_user_id         NUMBER;
    v_permit_no       VARCHAR2(50);

    v_permit_identity VARCHAR2(3);
    v_notif_identity  VARCHAR2(3);
    v_audit_identity  VARCHAR2(3);

    PROCEDURE add_audit_log (
        p_action  IN VARCHAR2,
        p_remarks IN VARCHAR2
    ) AS
    BEGIN
        IF v_audit_identity = 'YES' THEN
            INSERT INTO PAYMENT_AUDIT_LOG (
                payment_id,
                officer_id,
                action_taken,
                remarks,
                timestamp
            )
            VALUES (
                v_payment_id,
                p_officer_id,
                p_action,
                p_remarks,
                SYSDATE
            );
        ELSE
            INSERT INTO PAYMENT_AUDIT_LOG (
                audit_id,
                payment_id,
                officer_id,
                action_taken,
                remarks,
                timestamp
            )
            VALUES (
                AUDIT_SEQ.NEXTVAL,
                v_payment_id,
                p_officer_id,
                p_action,
                p_remarks,
                SYSDATE
            );
        END IF;
    END add_audit_log;


    PROCEDURE add_notification (
        p_type    IN VARCHAR2,
        p_subject IN VARCHAR2,
        p_message IN VARCHAR2
    ) AS
    BEGIN
        IF v_notif_identity = 'YES' THEN
            INSERT INTO NOTIFICATION (
                user_id,
                type,
                subject,
                message_body,
                sent_at,
                is_read
            )
            VALUES (
                v_user_id,
                p_type,
                p_subject,
                p_message,
                SYSDATE,
                0
            );
        ELSE
            INSERT INTO NOTIFICATION (
                notification_id,
                user_id,
                type,
                subject,
                message_body,
                sent_at,
                is_read
            )
            VALUES (
                NOTIF_SEQ.NEXTVAL,
                v_user_id,
                p_type,
                p_subject,
                p_message,
                SYSDATE,
                0
            );
        END IF;
    END add_notification;

BEGIN
    /*
      Check actual table definitions.
      If ID column is identity, we omit it.
      If ID column is not identity, we insert sequence value.
    */
    SELECT NVL(MAX(identity_column), 'NO')
    INTO v_permit_identity
    FROM user_tab_columns
    WHERE table_name = 'LEARNER_PERMIT'
      AND column_name = 'PERMIT_ID';

    SELECT NVL(MAX(identity_column), 'NO')
    INTO v_notif_identity
    FROM user_tab_columns
    WHERE table_name = 'NOTIFICATION'
      AND column_name = 'NOTIFICATION_ID';

    SELECT NVL(MAX(identity_column), 'NO')
    INTO v_audit_identity
    FROM user_tab_columns
    WHERE table_name = 'PAYMENT_AUDIT_LOG'
      AND column_name = 'AUDIT_ID';


    SELECT payment_id, payment_type, user_id
    INTO v_payment_id, v_payment_type, v_user_id
    FROM PAYMENT
    WHERE application_id = p_app_id
    ORDER BY payment_id DESC
    FETCH FIRST 1 ROWS ONLY;


    UPDATE PAYMENT
    SET payment_status = 'APPROVED',
        reviewed_by_officer_id = p_officer_id,
        remarks = 'Payment Verified by Officer'
    WHERE payment_id = v_payment_id;


    add_audit_log(
        'APPROVED',
        'Payment Verified by Officer'
    );


    IF v_payment_type = 'LICENSE_FEE' THEN

        UPDATE APPLICATION
        SET current_stage = 'LICENSE_GENERATION_PENDING',
            application_status = 'IN_PROGRESS'
        WHERE application_id = p_app_id;

        add_notification(
            'PAYMENT_APPROVED',
            'Payment Approved',
            'Your License Fee is verified.'
        );

    ELSE

        DELETE FROM LEARNER_PERMIT
        WHERE application_id = p_app_id;

        v_permit_no := 'LP-' || TO_CHAR(SYSDATE, 'YYYY') || '-' || p_app_id;

        IF v_permit_identity = 'YES' THEN
            INSERT INTO LEARNER_PERMIT (
                application_id,
                learner_permit_no,
                issue_date,
                expiry_date,
                status
            )
            VALUES (
                p_app_id,
                v_permit_no,
                SYSDATE,
                ADD_MONTHS(SYSDATE, 6),
                'ACTIVE'
            );
        ELSE
            INSERT INTO LEARNER_PERMIT (
                permit_id,
                application_id,
                learner_permit_no,
                issue_date,
                expiry_date,
                status
            )
            VALUES (
                PERMIT_SEQ.NEXTVAL,
                p_app_id,
                v_permit_no,
                SYSDATE,
                ADD_MONTHS(SYSDATE, 6),
                'ACTIVE'
            );
        END IF;


        UPDATE APPLICATION
        SET current_stage = 'LEARNER_ISSUED',
            application_status = 'IN_PROGRESS'
        WHERE application_id = p_app_id;

        add_notification(
            'PERMIT_ISSUED',
            'Permit Issued',
            'Your Learner Permit has been issued.'
        );

    END IF;

    COMMIT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(
            -20002,
            'No payment found for application_id: ' || p_app_id
        );

    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(
            -20001,
            'Procedure failed: ' || SQLERRM
        );
END;
/

-- ---------------------------------------------------------
-- 5. TRIGGERS
-- ---------------------------------------------------------

create or replace NONEDITIONABLE TRIGGER TRG_FORMAT_VIOLATION
BEFORE INSERT OR UPDATE ON TRAFFIC_VIOLATION
FOR EACH ROW
BEGIN
    IF :NEW.vehicle_reg_no IS NOT NULL THEN
        :NEW.vehicle_reg_no := UPPER(:NEW.vehicle_reg_no);
    END IF;
END;
/

create or replace NONEDITIONABLE TRIGGER TRG_LOCK_PAID_CHALLAN
BEFORE UPDATE ON TRAFFIC_VIOLATION
FOR EACH ROW
BEGIN
    -- If the challan is PAID, block anyone trying to alter the fine amount.
    IF :OLD.challan_status = 'PAID' AND :NEW.fine_amount != :OLD.fine_amount THEN
        RAISE_APPLICATION_ERROR(-20010, 'Security Error: Cannot modify the fine amount of a PAID challan.');
    END IF;
END;
/

create or replace NONEDITIONABLE TRIGGER TRG_PROTECT_AUDIT_LOG
BEFORE DELETE ON PAYMENT_AUDIT_LOG
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20013, 'Compliance Error: Deletion of Payment Audit Logs is strictly prohibited.');
END;
/

create or replace NONEDITIONABLE TRIGGER TRG_VALIDATE_FINES
BEFORE INSERT OR UPDATE ON TRAFFIC_VIOLATION
FOR EACH ROW
BEGIN
    -- Prevent negative fine amounts
    IF :NEW.fine_amount < 0 THEN
        RAISE_APPLICATION_ERROR(-20017, 'Database Error: Fine amount cannot be negative.');
    END IF;

    -- Prevent negative penalty points
    IF :NEW.penalty_points < 0 THEN
        RAISE_APPLICATION_ERROR(-20018, 'Database Error: Penalty points cannot be negative.');
    END IF;
END;
/

create or replace NONEDITIONABLE TRIGGER TRG_VALIDATE_LICENSE_DATES
BEFORE INSERT OR UPDATE ON DRIVING_LICENSE
FOR EACH ROW
BEGIN
    -- Ensure expiry date is always after the issue date
    IF :NEW.expiry_date <= :NEW.issue_date THEN
        RAISE_APPLICATION_ERROR(-20015, 'Database Error: License expiry date must be after the issue date.');
    END IF;

    -- If a license is suspended, ensure the suspension end date is actually set
    IF :NEW.status = 'SUSPENDED' AND :NEW.suspension_end_date IS NULL THEN
        RAISE_APPLICATION_ERROR(-20016, 'Database Error: A suspended license must have a suspension end date.');
    END IF;
END;
/

create or replace NONEDITIONABLE TRIGGER TRG_VALIDATE_PERMIT_DATES
BEFORE INSERT OR UPDATE ON LEARNER_PERMIT
FOR EACH ROW
BEGIN
    IF :NEW.expiry_date <= :NEW.issue_date THEN
        RAISE_APPLICATION_ERROR(-20011, 'Data Integrity Error: Expiry date must be strictly after the Issue date.');
    END IF;
END;
/

create or replace NONEDITIONABLE TRIGGER TRG_VALIDATE_TEST_DATE
BEFORE INSERT OR UPDATE ON DRIVING_TEST_SCHEDULE
FOR EACH ROW
BEGIN
    -- Ensure the scheduled date is never in the past
    IF TRUNC(:NEW.scheduled_date) < TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20014, 'Database Error: Cannot schedule a driving test in the past.');
    END IF;
END;
/

COMMIT;