package com.dlms.model.enums;

public enum ApplicationStage {
    LEARNER_PAYMENT_PENDING,
    PAYMENT_VERIFICATION,
    LEARNER_FEE_PENDING,
    LEARNER_ISSUED,
    FINAL_PAYMENT_VERIFICATION,
    LICENSE_FEE_PENDING,
    LICENSE_GENERATION_PENDING,
    FINAL_REVIEW,
    LICENSE_READY,
    COMPLETED,
    REJECTED,
    MEDICAL_PENDING,
    DOCS,
    THEORY_PENDING,
    PRACTICAL_PENDING,
    TESTS_PENDING,
    LICENSE_PAYMENT_PENDING
}